Repository WebMailSystem/WebMailSystem, pull requests merged in 2023-05, with the labels that each got.

#30 feat : 메일 읽기 기능 모드에서 메일 삭제 기능 구현 (#29)
  src/main/java/deu/cse/spring_webmail/control/ReadController.java
  src/main/webapp/WEB-INF/views/read_mail/sidebar_read_menu.jsp
Labels: 💎 Feature, 💎민수💎

#36 feat : wysiwyg (#35)
  src/main/java/deu/cse/spring_webmail/model/RecyclebinService.java
  src/main/java/deu/cse/spring_webmail/repository/InboxRepository.java
  src/main/webapp/WEB-INF/download/wjdrltjr5/이미지.jfif
  src/main/webapp/WEB-INF/views/write_mail/write_mail.jsp
Labels: 💎 Feature, 💎기석💎

#38 fix : messageToInbox error (#37)
  src/test/java/deu/cse/spring_webmail/unittest/InboxRepositoryTest.java
Labels: ❗ Hotfix, 💎민수💎

#39 feat : 메일 복수 삭제 기능 (#31)
  src/main/java/deu/cse/spring_webmail/control/ReadController.java
  src/main/java/deu/cse/spring_webmail/model/MessageFormatter.java
Labels: 💎 Feature, 💎민수💎

#51 Fix/xssfilter
  src/main/resources/lucy-xss-sax.xml
  src/main/resources/lucy-xss-servlet-filter-rule.xml
Labels: 🐞 Bug, 💎기석💎

#59 Feature/admin maintenance
  src/main/java/deu/cse/spring_webmail/config/CustomSuccessHandler.java
  src/main/java/deu/cse/spring_webmail/config/WebSecurityConfig.java
  src/main/java/deu/cse/spring_webmail/control/AdminService.java
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/webapp/WEB-INF/views/admin/add_user.jsp
  src/main/webapp/WEB-INF/views/admin/change_password.jsp
  src/main/webapp/WEB-INF/views/admin/sidebar_admin_menu.jsp
Labels: 💎 Feature, ❗ Hotfix, 🛠 Fix, 💎민수💎

#62 fix : 메일 페이징 처리 (#61)
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/java/deu/cse/spring_webmail/model/MessageFormatter.java
  src/main/java/deu/cse/spring_webmail/repository/InboxRepository.java
  src/main/resources/static/css/main_style.css
  src/main/webapp/WEB-INF/views/main_menu.jsp
Labels: 💎 Feature, ♻️ Refactor, 💎민수💎

#64 Feature/comment clean up
  src/main/java/deu/cse/spring_webmail/control/AdminService.java
  src/main/java/deu/cse/spring_webmail/control/SentMailController.java
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/java/deu/cse/spring_webmail/dto/SignupForm.java
  src/main/java/deu/cse/spring_webmail/entity/Inbox.java
  src/main/java/deu/cse/spring_webmail/entity/Recyclebin.java
  src/main/java/deu/cse/spring_webmail/entity/Users.java
  src/main/java/deu/cse/spring_webmail/model/CustomUserDetails.java
  src/main/java/deu/cse/spring_webmail/model/MessageFormatter.java
  src/main/java/deu/cse/spring_webmail/model/Pop3Agent.java
  src/main/java/deu/cse/spring_webmail/model/SmtpAgent.java
  src/main/java/deu/cse/spring_webmail/model/UserAdminAgent.java
  src/main/java/deu/cse/spring_webmail/repository/AddrsRepository.java
  src/main/java/deu/cse/spring_webmail/repository/RecyclebinRepository.java
  src/main/webapp/WEB-INF/views/admin/admin_menu.jsp
  src/main/webapp/WEB-INF/views/admin/delete_user.jsp
  src/main/webapp/WEB-INF/views/admin/sidebar_admin_menu.jsp
  src/main/webapp/WEB-INF/views/footer.jspf
  src/main/webapp/WEB-INF/views/header.jspf
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/login_fail.jsp
  src/main/webapp/WEB-INF/views/write_mail/write_mail_1.jsp
Labels: 🚿 Clean-Up, 💎민수💎

#68 feat : 메일 제거 재확인 알림 추가 (#67)
  src/main/java/deu/cse/spring_webmail/model/MessageFormatter.java
  src/main/webapp/WEB-INF/views/main_menu.jsp
  src/main/webapp/WEB-INF/views/recyclebin.jsp
Labels: 💎 Feature, 💎민수💎
